version: '3.7'
services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
  
  pgadmin:
    image: dpage/pgadmin4:4.22
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: passw0rd
    ports:
      - 5050:80
